version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:17.4-alpine3.21
    restart: always
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - ./PGDATA:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "psql -U ${DATABASE_USER} -d ${DATABASE_NAME} -c 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 5
      start_period: 5s
